_target_: "mask_ml.model.auto_encoder.MaskedAutoEncoder"
encoder:
  _target_: "mask_ml.model.mlp.MLP"
  activation_function: "relu"
  input_size: 200  # Input size from patch embeddings
  output_size: 200  # Keep consistent with decoder input_size
  hidden_sizes: [150, 120]
decoder:
  _target_: "mask_ml.model.mlp.MLP"
  activation_function: "relu"
  input_size: 200  # Should match encoder output_size
  output_size: 16   # Patch size (4x4) * channels (1) = 16
  hidden_sizes: [120, 150]

# Basic configuration
mask_ratio: 0.75
image_size: 28     # MNIST images are 28x28
patch_size: 4      # Using 4x4 patches for MNIST
num_channels: 1    # MNIST is grayscale (1 channel)
embedded_size: 200 # Embedding dimension
