defaults:
  - encoder: vit_encoder
  - decoder: mask_decoder  # Assuming mask_decoder.yaml is in the model directory

model_name: SegmentationAutoEncoder


  segmentation_auto_encoder:
    _target_: "path.to.SegmentationAutoEncoderConfig"
    encoder_config:
      transformer_blocks: 12
      image_size: 224
      patch_size: 16
      num_channels: 3
      encoder_stride: 4
      positional_embedding: "sine"
      embedded_size: 768
      attention_heads: 12
      mlp_hidden_size: 3072
      mlp_layers: 2
      activation_function: "relu"
      dropout_prob: 0.1
    decoder_config:
      transformer_blocks: 6
      num_multimask_outputs: 3
      iou_mlp_depth: 2