
vit_classification:
    _target_: "path.to.VitClassificationConfig"
    transformer_blocks: 12
    image_size: 224
    patch_size: 16
    num_channels: 3
    encoder_stride: 4
    positional_embedding: "sine"
    embedded_size: 768
    attention_heads: 12
    mlp_hidden_size: 3072
    mlp_layers: 2
    activation_function: "relu"
    dropout_prob: 0.1
    num_classes: 1000