

_target_: "mask_ml.model.vit.VitClassificationConfig"
input_size: 784
num_classes: 10
model_config:
    _target_: "mask_ml.model.vit.ViTConfig"
    transformer_blocks: 1
    image_size: 32
    patch_size: 16
    num_channels: 1
    encoder_stride: 4
    positional_embedding: "sinusoidal"
    embedded_size: 784
    attention_heads: 4
    mlp_hidden_size: 3072
    mlp_layers: 2
    activation_function: "relu"
    dropout_prob: 0.1