#!/bin/bash
set -e

# Define script shortcuts with friendly names
declare -A SCRIPT_OPTIONS
SCRIPT_OPTIONS["cutie_demo"]="demo/sam_cutie_video_segmentation.py"
SCRIPT_OPTIONS["dsn_demo"]="demo/dsn_cutie_video_segmentation.py"
SCRIPT_OPTIONS["train_yolo"]="demo/ultralytics_training.py"
# Add more predefined options here as needed
# SCRIPT_OPTIONS["another_demo"]="path/to/another_script.py"

# Options for accessing the volume directory
SCRIPT_OPTIONS["volume_cutie_demo"]="volume/demo/sam_cutie_video_segmentation.py"
SCRIPT_OPTIONS["volume_dsn_demo"]="volume/demo/dsn_cutie_video_segmentation.py"
SCRIPT_OPTIONS["volume_ultralytics_training"]="volume/demo/ultralytics_training.py"

# Default option if none specified
DEFAULT_OPTION="cutie_demo"
DEFAULT_SCRIPT=${SCRIPT_OPTIONS[$DEFAULT_OPTION]}

# Flag to control whether container stays alive after script execution
KEEP_ALIVE=true

# Function to list all available options
list_options() {
    echo "Available script options:"
    for option in "${!SCRIPT_OPTIONS[@]}"; do
        echo "  - $option: ${SCRIPT_OPTIONS[$option]}"
    done
    echo ""
}

# Check if help is requested
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo "Usage: docker run ... [-e SCRIPT_OPTION=option_name] [script_args...]"
    echo "   or: docker run ... [-e SCRIPT_TO_RUN=path/to/script.py] [script_args...]"
    echo ""
    echo "Common script options:"
    echo "  - cutie_demo: Run SAM Cutie video segmentation tool"
    echo "  - train_yolo: Run Ultralytics training on data generated by SAM Cutie"
    echo ""
    echo "Special flags:"
    echo "  --keep-alive: Keep the container running after script completion"
    echo ""
    echo "Example for SAM Cutie:"
    echo "  ./run_docker_demo.sh -s cutie_demo -- --save-yolo --keep-alive"
    echo ""
    echo "Example for Ultralytics training:"
    echo "  ./run_docker_demo.sh -s train_yolo -- --data-dir output --model yolov8n.pt --keep-alive"
    echo ""
    list_options
    exit 0
fi

# Process special flags
for arg in "$@"; do
    if [[ "$arg" == "--keep-alive" ]]; then
        KEEP_ALIVE=true
        # Remove --keep-alive from arguments
        set -- "${@/--keep-alive/}"
    fi
done

# Determine which script to run
SCRIPT_PATH=""

# First check if a predefined option was selected
if [ ! -z "$SCRIPT_OPTION" ]; then
    if [[ -n "${SCRIPT_OPTIONS[$SCRIPT_OPTION]}" ]]; then
        echo "Using predefined option: $SCRIPT_OPTION"
        SCRIPT_PATH="${SCRIPT_OPTIONS[$SCRIPT_OPTION]}"
    else
        echo "Warning: Unknown option '$SCRIPT_OPTION'"
        list_options
        echo "Defaulting to: ${DEFAULT_SCRIPT}"
        SCRIPT_PATH="${DEFAULT_SCRIPT}"
    fi
# Check if SCRIPT_TO_RUN environment variable is set
elif [ -z "$SCRIPT_TO_RUN" ]; then
    echo "SCRIPT_TO_RUN not specified, defaulting to ${DEFAULT_SCRIPT}"
    SCRIPT_PATH="${DEFAULT_SCRIPT}"
else
    echo "Running specified script: ${SCRIPT_TO_RUN}"
    SCRIPT_PATH="${SCRIPT_TO_RUN}"
fi

# Check if the script exists
if [ ! -f "${SCRIPT_PATH}" ]; then
    echo "Error: Script ${SCRIPT_PATH} does not exist!"
    exit 1
fi

# Check if additional args were provided
if [ $# -gt 0 ]; then
    echo "Running: python ${SCRIPT_PATH} $@"
    python "${SCRIPT_PATH}" "$@"
else
    echo "Running: python ${SCRIPT_PATH}"
    python "${SCRIPT_PATH}"
fi

# Keep the container running if requested
if [ "$KEEP_ALIVE" = true ]; then
    echo ""
    echo "====================================================="
    echo "Script execution completed, but container kept alive."
    echo "You can now run additional commands in the container."
    echo "Type 'exit' to end the session and stop the container."
    echo "====================================================="
    echo ""
    # Start an interactive shell
    /bin/bash
fi
