#!/bin/bash

# Display usage information
function show_help {
    echo "Usage: $0 [options] [-- script_args]"
    echo ""
    echo "Options:"
    echo "  -h, --help                Show this help message"
    echo "  -s, --script NAME         Specify which script to run (e.g., cutie_demo, train_yolo)"
    echo "  -v, --video PATH          Specify video file path (will be mounted inside container)"
    echo "  -o, --output-dir DIR      Specify output directory"
    echo ""
    echo "Common script options:"
    echo "  - cutie_demo: Run SAM Cutie video segmentation tool"
    echo "  - train_yolo: Run Ultralytics training on data generated by SAM Cutie"
    echo "  - volume_cutie_demo: Run SAM Cutie from the volume directory"
    echo "  - volume_ultralytics_training: Run Ultralytics training from the volume directory"
    echo ""
    echo "Examples:"
    echo "  # Run the SAM Cutie tool and save frames & YOLO annotations:"
    echo "  $0 -s cutie_demo -- --save-yolo"
    echo ""
    echo "  # Run Ultralytics training on the generated data:"
    echo "  $0 -s train_yolo -- --data-dir output --model yolov8n.pt"
    echo ""
    echo "  # Run the SAM Cutie tool with a specific video file:"
    echo "  $0 -s cutie_demo -v /path/to/video.mp4 -- --save-yolo"
    echo ""
    echo "  # Run from the volume directory:"
    echo "  $0 -s volume_cutie_demo -- --save-yolo"
    echo "  $0 -s volume_ultralytics_training -- --data-dir output --model yolov8n.pt"
    echo ""
    echo "NOTE: Do not use multiple -- separators in your command"
    echo ""
}

# Default values
SCRIPT_OPTION="cutie_demo"
VIDEO_PATH=""
OUTPUT_DIR="output"
ADDITIONAL_ARGS=""

# Parse command line arguments before --
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_help
            exit 0
            ;;
        -s|--script)
            SCRIPT_OPTION="$2"
            shift 2
            ;;
        -v|--video)
            # Get absolute path for proper mounting
            VIDEO_PATH=$(realpath "$2")
            shift 2
            ;;
        -o|--output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --)
            shift
            # Collect all remaining arguments as script arguments
            # Remove any additional -- from the arguments
            for arg in "$@"; do
                if [ "$arg" != "--" ]; then
                    ADDITIONAL_ARGS="$ADDITIONAL_ARGS $arg"
                fi
            done
            break
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"
OUTPUT_PATH=$(realpath "$OUTPUT_DIR")

# Get the absolute path to the project directory
PROJECT_DIR=$(realpath "$(dirname "$0")")

# Prepare Docker volume mounts
VOLUMES="-v $OUTPUT_PATH:/MASK_ML/output -v $PROJECT_DIR:/MASK_ML/volume"

# If video path was provided, add it as a volume and prepare the script argument
if [ -n "$VIDEO_PATH" ]; then
    VIDEO_DIR=$(dirname "$VIDEO_PATH")
    VIDEO_FILENAME=$(basename "$VIDEO_PATH")
    VOLUMES="$VOLUMES -v $VIDEO_DIR:/input"
    # Add video flag to additional args if not already there
    if [[ ! "$ADDITIONAL_ARGS" =~ "--video" ]]; then
        ADDITIONAL_ARGS="$ADDITIONAL_ARGS --video /input/$VIDEO_FILENAME"
    fi
fi

# Allow local X server connections for GUI
xhost +local:docker

# Run the Docker container with all specified options
echo "Running with script option: $SCRIPT_OPTION"
echo "Additional arguments: $ADDITIONAL_ARGS"

# Use docker compose run with --no-deps to isolate this service run and explicitly override the command
docker compose run --rm --no-deps $VOLUMES \
    -e SCRIPT_OPTION="$SCRIPT_OPTION" \
    mask_ml_app $ADDITIONAL_ARGS



