datasets:
  coco:
    download:
    base_dir: /sadf/adf
    coco_train:
      image_dir: /train
      annotation_dir: /val


    coco_val:
      image_dir: /val
      annotation_dir: /val


  sa1b:
    download: False
    base_dir: /asdf/ads
    sa1b_train:
      image_dir: /train
      annotation_dir: /asdf
    sa1b_val:
      image_dir: /asdf
      annotation_dir: /asf

  
