defaults:
  - _self_
  - datasets: coco_segmentation  


#Experiment
output_dir: ./runs
experiment_name: autoencoder
learning_rate: 0.00002
transfer_learning_weights: ""
epochs: 1
# Data
image_reshape: 32
batch_size: 8
