defaults:
  - _self_

# Docker execution settings
use_docker: true

# Data paths
video_dir: /mnt/data/videos
output_dir: ./runs

# Pipeline task settings
data_engine_task: "video_segmentation_"  # Options: video_segmentation, model_training, full_pipeline
