defaults:
  - _self_
  - model: image_auto_encoder
  - datasets: mnist_classification
  - override hydra/sweeper: optuna
output_dir: ./runs
experiment_name: vit_eval_rr
transfer_learning_weights: ""
# Data
image_reshape: 32
batch_size: 8

attention_heads: []  # Indices of attention heads to visualize
num_batches: 3  # Number of random batches to visualize