defaults:
  - model: vit_classification
  - datasets: classification

output_dir: ./runs
dataset: cifar100
task: classification
batch_size: 8
learning_rate: 0.0005
image_size: 256
epochs: 11
attention_heads: [1]
