defaults:
  - model: vit_classification
  - datasets: classification

output_dir: ./runs
experiment_name: cifar100
dataset: cifar100
task: classification
batch_size: 32
learning_rate: 0.000002
image_size: 256
epochs: 11
saved_weight_path: ""
visualization:
  attention_heads: [1]
