defaults:
  - _self_
  - datasets: mnist_classification  
  - model : mlp_classification
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.OptunaSweeper
    direction: minimize  # Set this to "maximize" if optimizing for accuracy
    n_trials: 50  # Number of Optuna trials
    search_space:
      learning_rate: interval(1e-5, 1e-2)  # Learning rate search space
      transformer_blocks: range(8, 16)  # Search space for transformer blocks
      mlp_hidden_size: range(1024, 4096)  # Search space for MLP hidden size
      dropout_prob: interval(0.0, 0.5)  # Search space for dropout probability


output_dir: ./runs
experiment_name: mnisttry
task: mlp_classification
batch_size: 4
learning_rate: 0.00002
image_size: 32
epochs: 1
saved_weight_path: ""
visualization:
  attention_heads: [1]