defaults:
  - _self_
  - datasets: mnist_classification
  - model: image_auto_encoder
  - loss_function: mse
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.OptunaSweeper
    direction: minimize  # Set this to "maximize" if optimizing for accuracy
    n_trials: 50  # Number of Optuna trials
    search_space:
      learning_rate: interval(1e-5, 1e-2)  # Learning rate search space
      transformer_blocks: range(8, 16)  # Search space for transformer blocks
      mlp_hidden_size: range(1024, 4096)  # Search space for MLP hidden size
      dropout_prob: interval(0.0, 0.5)  # Search space for dropout probability

# Experiment
output_dir: ./runs
experiment_name: vit
epochs: 1
batch_size: 4
learning_rate: 0.00002
image_reshape: 32
transfer_learning_weights: ""

# Visualization
attention_heads: [0]  # Indices of attention heads to visualize
num_batches: 3  # Number of random batches to visualize

# Latent space visualization
latent_space_visualization: true
latent_sample_space_size: 100
latent_space_layer_name: 'encoder'
latent_space_pca_components: 2  # Number of PCA components for latent space visualization (2 or 3)